name: country_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  collection: ^1.16.0
  sliver_tools: ^0.2.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true



